### Recuperar todas las películas
GET http://localhost:1234/content

### Recuperar una película por id
GET http://localhost:1234/content/a0ec3e46-7c55-11ef-b756-309c23fb652b

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION

### Crear una película con POST
POST http://localhost:1234/content
Content-Type: application/json

{
  "title": "el señor terry",
  "mainContent": "Una larga historia q no estoy dispusto a escribir",
  "nameImage": "Francis Ford Coppola",
  "nameImage1": "string",
  "nameImage2": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "location": "https://www.youtube.com/watch?v=3h4Bzr8Zg9I",
  "entryPrice": 10,
  "timeTravel": 120
}

### Borrar una película
DELETE http://localhost:1234/content/a0ec3e46-7c55-11ef-b756-309c23fb652b

### Actualizar una película
PATCH http://localhost:1234/content/64d4da882f83563ab4f40632
Content-Type: application/json

{
  "year": 2022
}